<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add Datetime' => '',
  'D2files' => '',
  'Deleted' => '',
  'File Name' => '',
  'ID' => '',
  'Model' => '',
  'Notes' => '',
  'TYPE_DOCUMENT' => '',
  'TYPE_IMAGE' => '',
  'TYPE_OTHER' => '',
  'Type' => '',
  'Upload Path' => '',
  'User' => '',
  'tooltip.add_datetime' => '',
  'tooltip.deleted' => '',
  'tooltip.file_name' => '',
  'tooltip.id' => '',
  'tooltip.model' => '',
  'tooltip.model_id' => '',
  'tooltip.notes' => '',
  'tooltip.type' => '',
  'tooltip.upload_path' => '',
  'tooltip.user_id' => '',
  'You are not authorized to perform this action.' => 'Jūs neesat autorizēts veikt šo darbību.',
);
